spring:
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/local-data.sql

logging:
  level:
    com.sportygroup.settlement: DEBUG
